export const randomSentences = [
    "The sun sets beyond the horizon.",
    "Birds chirp in the early morning light.",
    "Books line the shelves of the old library.",
    "Laughter echoes through the empty hallway.",
    "Raindrops tap gently on the windowpane.",
    "The aroma of fresh coffee fills the room.",
    "Waves crash against the rocky shore.",
    "Stars twinkle in the midnight sky.",
    "A gentle breeze rustles the leaves.",
    "Children play in the park, their laughter infectious.",
    "The scent of flowers wafts through the garden.",
    "Clouds drift lazily across the azure sky.",
    "The old oak tree stands tall and proud.",
    "A solitary candle flickers in the darkness.",
    "Footsteps echo down the deserted street.",
    "The moon casts an ethereal glow over the landscape.",
    "A cat purrs contentedly in its owner's lap.",
    "The sound of distant thunder rumbles ominously.",
    "A rainbow arches across the sky after the rain.",
    "The smell of freshly baked bread fills the kitchen.",
    "Fireflies dance in the warm summer night.",
    "Snowflakes drift lazily to the ground.",
    "The sound of a distant train whistle fills the air.",
    "Leaves crunch underfoot in the autumn forest.",
    "A shooting star streaks across the heavens.",
    "The sound of a violin fills the concert hall.",
    "Waves gently lap against the side of the boat.",
    "The aroma of sizzling bacon fills the kitchen.",
    "Butterflies flit among the wildflowers.",
    "The sound of crickets chirping fills the night.",
    "A soft blanket of fog settles over the city.",
    "The crackling of a campfire fills the silence.",
    "Seagulls cry out as they soar overhead.",
    "The scent of pine fills the mountain air.",
    "Thunder rumbles in the distance, heralding a storm.",
    "The sound of church bells rings out across the town.",
    "Leaves rustle in the gentle breeze.",
    "The smell of freshly cut grass fills the air.",
    "A rainbow of colors fills the sky at sunset.",
    "The distant howl of a wolf echoes through the night.",
    "The sound of waves crashing against the shore is soothing.",
    "A cat stretches lazily in the sunbeam.",
    "The scent of lavender fills the garden.",
    "The distant cry of a loon breaks the stillness of the lake.",
    "The crackling of leaves underfoot is a sign of autumn.",
    "The sound of rain on the roof is comforting.",
    "The scent of pine needles fills the forest.",
    "The distant hum of traffic fills the air.",
    "Butterflies flutter by on delicate wings.",
    "The sound of a babbling brook is peaceful.",
    "The scent of roses fills the garden.",
    "The distant call of a bird breaks the silence of the morning.",
    "Leaves swirl in the autumn wind.",
    "The crackling of a bonfire warms the chilly night air.",
    "The scent of freshly baked cookies fills the kitchen.",
    "The sound of children laughing is infectious.",
    "Raindrops pitter-patter on the windowpane.",
    "The scent of cinnamon fills the air.",
    "The distant rumble of thunder signals an approaching storm.",
    "The sound of waves crashing against the rocks is mesmerizing.",
    "Leaves crunch underfoot on the forest floor.",
    "The scent of fresh rain fills the air.",
    "The distant howl of a coyote breaks the stillness of the night.",
    "The crackling of a fireplace is comforting on a cold night.",
    "The scent of pine cones fills the forest.",
    "The sound of a distant waterfall is soothing.",
    "Butterflies flit among the flowers in the garden.",
    "The scent of freshly baked bread is tantalizing.",
    "The distant cry of a seagull breaks the silence of the beach.",
    "Leaves rustle in the autumn breeze.",
    "The crackling of leaves underfoot is a sure sign of autumn.",
    "The scent of fresh coffee fills the kitchen.",
    "The distant honk of a goose breaks the silence of the lake.",
    "The sound of waves crashing against the shore is calming.",
    "Butterflies dance among the wildflowers in the meadow.",
    "The scent of lilacs fills the garden.",
    "The distant rumble of thunder signals an approaching storm.",
    "The crackling of a bonfire warms the chilly night air.",
    "The sound of rain on the roof is soothing.",
    "Leaves swirl in the autumn wind.",
    "The scent of freshly baked cookies fills the kitchen.",
    "The distant call of a bird breaks the silence of the morning.",
    "Raindrops pitter-patter on the windowpane.",
    "The scent of cinnamon fills the air.",
    "The distant rumble of thunder signals an approaching storm.",
    "The sound of waves crashing against the rocks is mesmerizing.",
    "Leaves crunch underfoot on the forest floor.",
    "The scent of fresh rain fills the air.",
    "The crackling of a fireplace is comforting on a cold night.",
    "The scent of pine cones fills the forest.",
    "The sound of a distant waterfall is soothing.",
    "Butterflies flit among the flowers in the garden.",
    "The scent of freshly baked bread is tantalizing.",
    "The distant cry of a seagull breaks the silence of the beach.",
    "Leaves rustle in the autumn breeze.",
    "The crackling of leaves underfoot is a sure sign of autumn.",
    "The scent of fresh coffee fills the kitchen.",
    "The distant honk of a goose breaks the silence of the lake.",
    "The sound of waves crashing against the shore is calming.",
    "Butterflies dance among the wildflowers in the meadow."
];
